### PR TITLE
Create build.yml

### PR DESCRIPTION
**Pull request by gkirchner**

### CODE REVIEW

**Comment by gkirchner** [comment]
The error is a circular dependency

**Comment by gkirchner** [comment]
The error is a circular dependency.

**Comment by gkirchner** [comment]
basic coupling of SonarCloud to project

**Review by Theophile-Madet — APPROVED** [review]

**Comment by oliveratfoodcoopx** [comment]
I think this PR covers the SonarCloud part of [#17](https://github.com/FoodCoopX/wirgarten-tapir/issues/17).

**Pull request merged**
