### PR TITLE
WLS-189 

### PR DESCRIPTION
**Pull request by Theophile-Madet**

### CODE REVIEW

**Comment by gkirchner** [comment]
I deploy this branch now to ln-stage.

**Comment by gkirchner** [comment]
@Theophile-Madet The PR now has conflicts with the integrate-tapir-mail after I merged the previous PR. Could you look for it please?

**Comment by Theophile-Madet** [comment]
@gkirchner Fixed! Let me know if the other branches need something too.

**Comment by gkirchner** [comment]
Cool, thnx!

**Pull request merged**
